[package]
name = "show_image"
version = "0.1.0"
edition = "2021"

[dependencies]
winapi = { version = "0.3", features = ["winuser", "wingdi", "libloaderapi", "windef", "minwindef", "objbase", "combaseapi"] }
rand = "0.8"
png = "0.17"