[manifest]
version = "1.0.0"
dump_lua = true
priority = 4


[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''local last_mult = self.ability.mult'''
position = 'after'
match_indent = true
payload = '''
    if last_mult >= 25 then
        CHAR.FUNC.overclock_proc({card=self,key="j_charcuterie_metro_lines"})
        return {}
    end
'''
[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = '''if self.ability.name == 'Castle' and
            not context.other_card.debuff and
            context.other_card:is_suit(G.GAME.current_round.castle_card.suit) and not context.blueprint then'''
position = 'after'
match_indent = true
payload = '''
    if self.ability.extra.chips >= 200 then
        CHAR.FUNC.overclock_proc({card=self,key='j_charcuterie_bunker',save=true})
        return {}
    end
'''
